DELIMITER $$
CREATE PROCEDURE SP_AUDITORIA_JUAN (
p_MENSAJE VARCHAR (100)
IN p_forma_pago VARCHAR(50),
IN p_id_transaccion INT,
IN p_fecha_pago DATE,
IN p_total DECIMAL (15,2)
)
BEGIN

DECLARE V_EXISTE_ID_TRAN VARCHAR(50);

SELECT COUNT(*)
INTO V_EXISTE_ID_TRAN
FROM PAGO WHERE ID_TRANSACCION = P_ID_TRANSACCION;

IF V_EXISTE_ID_TRAN = 0
THEN

INSERT INTO PAGO (codigo_cliente, forma_pago, id_transaccion, fecha_pago, total)
VALUES (p_codigo_cliente, p_forma_pago, p_id_transaccion, p_fecha_pago, p_total);

END IF;
END $$
DELIMITER ;

CREATE EVENT AUDITORIA_JUAN
ON SCHEDULE EVERY 1 MINUTE 
DO
INSERT INTO LOGS (MENSAJE)
VALUES ('EJECUTADO DESDE EVENTO');


SHOW EVENTS;


SHOW VARIABLES LIKE 'EVENT_SCHEDULER';

SELECT * FROM LOGS
